### ISSUE TITLE
Providing a schema is problematic

### ISSUE THREAD

**Issue by abellgithub** [stac-extensions/pointcloud#2]
I'm not sure what information one is trying to convey with the schema definition, but it doesn't map well to the most common point cloud formats (LAS, LAZ). I'm not sure what the motivation for the schema is, so I can't suggest any change, but the logic for the schema should be well-defined.

**Comment by gadomski** [comment]
I _think_ schema is supposed to map to `pdal info --schema` output?

**Comment by gadomski** [comment]
Considering this closed by https://github.com/stac-extensions/pointcloud/pull/11.
