### ISSUE TITLE
Relax schema from required to optional

### ISSUE THREAD

**Issue by hobu** [stac-extensions/pointcloud#3]
When used in practice, the schema object doesn't add a ton of value, and more importantly, I don't know that anyone is going to be using such a complex object to be filtering data. It's either a point cloud with XYZ position values or it's not. 

I think we should relax the schema object to optional.

cc @kylemann16

**Comment by raelwaed** [comment]
I agree with you @hobu in terms of the way I and my client want to search for information.
- pc:count - fair enough
- pc:type - also good
- pc:encoding - isn't this covered by the type field in the Asset Object already?

I think getting stats on the classification is largely a waste of time, but getting actual classifications has more value.

**Comment by wonder-sk** [comment]
I would suggest to change schema to just a list of attributes: `["X", "Y", "Z", "Intensity", "Classification", ...]`

I don't see much use of `type` and `size` in a catalog, it's a technical detail that is only making the definition more verbose.
