### ISSUE TITLE
Better define or remove pc:encoding

### ISSUE THREAD

**Issue by wonder-sk** [stac-extensions/pointcloud#6]
The definition of the required `pc:encoding` says that it is "Content encoding or format of the data."

With this kind of vague definition I am not sure if it adds any value - writers will put there something but readers will not be able to rely on those values.

I would suggest to either improve the definition to make it clear what to expect (at least for the commonly expected encodings) or to just remove it.

**Comment by m-mohr** [comment]
What's the difference to the type found in assets anyway?
