### ISSUE TITLE
pdal-to-stac.py doesn't work out of the box with instructions given

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/pointcloud#7]
I've followed the instructions in the file itself, but it's missing installing the conda packages gdal and the Python packages json, ogr and osr it seems. Installing gdal and json was not a problem, but I'm not 100% sure where to get the Python packages ogr and osr from. GDAL Python bindings?

**Comment by jlaura** [comment]
Piling on here, once these are installed, pdal-to-stac.py fails when the files are not convertible to WGS84 by PROJ. This is not a point cloud issue, but is surprising when one tries to create a STAC metadata file from a COPC/LAZ file.

**Comment by gadomski** [comment]
>  pdal-to-stac.py fails when the files are not convertible to WGS84 by PROJ. This is not a point cloud issue, but is surprising when one tries to create a STAC metadata file from a COPC/LAZ file.

Yeah, the script is pretty bare-bones. I'll add a note to https://github.com/stac-extensions/pointcloud/pull/10 that it's not meant for production usage, and point people to https://github.com/stactools-packages/pointcloud/ for more general-use "make STAC from a point cloud file" library?
